version: '3'

services:
  react-app:
    container_name: react-base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # host dir:container dir
      - ./app:/app
    environment:
      - NODE_DEV=development
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "cd /app/react-sample && npm start"
    ports:
       - 3000:3000
    tty: true
    stdin_open: true
 